const resMenu = {
  "@type": "type.googleapis.com/swiggy.presentation.food.v2.ItemCategory",
  title: "Recommended",
  itemCards: [
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "112620245",
          name: "Chicken Maharaja Mac",
          category: "Gourmet Burger and Meals",
          description:
            "Enjoy the tallest burgers innovated by us. Created with chunky juicy grilled chicken patty paired along with fresh ingredients like jalape??o, onion, slice of cheese, tomatoes & crunchy lettuce dressed with the classical Habanero sauce.",
          imageId: "106e6e88e435a05c69e170534dc7f5e6",
          inStock: 1,
          price: 24667,
          variants: {},
          variantsV2: {},
          itemAttribute: {
            vegClassifier: "NONVEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.3",
              ratingCount: "59 ratings",
              ratingCountV2: "59",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "112620318",
          name: "McSaver McSpicy Premium Chicken Meal",
          category: "Gourmet Burger and Meals",
          description:
            "A deliciously filling meal of McSpicy Premium Chicken Burger + Fries (M) + Drink of your choice",
          imageId: "d437eb722f457c66f26a087b789c056f",
          inStock: 1,
          price: 38477,
          variants: {},
          variantsV2: {},
          addons: [
            {
              groupId: "82870259",
              groupName: "Choose an option",
              choices: [
                {
                  id: "67791259",
                  name: "Cappuccino (R)",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791254",
                  name: "Sprite",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791265",
                  name: "McCafe-Chocolate Frappe",
                  price: 18400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791253",
                  name: "Fanta",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791264",
                  name: "Strawberry Chiller",
                  price: 8600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791263",
                  name: "McCafe-Mocha Frappe",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791274",
                  name: "Berry Lemonade Splash Regular",
                  price: 3800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791269",
                  name: "Lemon Chiller",
                  price: 4800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791257",
                  name: "Mocha (S)",
                  price: 11600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791268",
                  name: "McCafe-Ice Coffee",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791256",
                  name: "Latte (S)",
                  price: 3700,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791267",
                  name: "Green Apple Chiller",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791255",
                  name: "Hot Chocolate (S)",
                  price: 5100,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791261",
                  name: "Mocha (R)",
                  price: 14200,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791272",
                  name: "American Mud Pie",
                  price: 6300,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791260",
                  name: "Hot Chocolate (R)",
                  price: 8400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "93041905",
                  name: "Latte (R)",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
              ],
              maxAddons: 1,
              maxFreeAddons: -1,
            },
          ],
          itemAttribute: {
            vegClassifier: "NONVEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.1",
              ratingCount: "15 ratings",
              ratingCountV2: "15",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "112620347",
          name: "Veg Maharaja Mac",
          category: "Gourmet Burger and Meals",
          description:
            "Enjoy the tallest burgers innovated by us. Created with perfectly fried corn and cheese patty paired along with fresh ingredients like jalape??o, onion, slice of cheese & crunchy lettuce dressed with cocktail sauce.",
          imageId: "b85e6c16297b0c9127b8d08c93293cf7",
          inStock: 1,
          isVeg: 1,
          price: 22000,
          variants: {},
          variantsV2: {},
          itemAttribute: {
            vegClassifier: "VEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.4",
              ratingCount: "21 ratings",
              ratingCountV2: "21",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "115128775",
          name: "McSaver Chicken Maharaja Mac Meal",
          category: "Gourmet Burger and Meals",
          description:
            "Enjoy a double decker Chicken Maharaja Mac + Fries (M) + Drink of your Choice . Order now to experience a customizable, delicious meal.",
          imageId: "97932df813e65713ddd0808e77bb201e",
          inStock: 1,
          price: 38477,
          variants: {},
          variantsV2: {},
          addons: [
            {
              groupId: "88794435",
              groupName: "Choose an option",
              choices: [
                {
                  id: "67791259",
                  name: "Cappuccino (R)",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791254",
                  name: "Sprite",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791265",
                  name: "McCafe-Chocolate Frappe",
                  price: 18400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791253",
                  name: "Fanta",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791264",
                  name: "Strawberry Chiller",
                  price: 8600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791263",
                  name: "McCafe-Mocha Frappe",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791274",
                  name: "Berry Lemonade Splash Regular",
                  price: 3800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791269",
                  name: "Lemon Chiller",
                  price: 4800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791257",
                  name: "Mocha (S)",
                  price: 11600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791268",
                  name: "McCafe-Ice Coffee",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791256",
                  name: "Latte (S)",
                  price: 3700,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791267",
                  name: "Green Apple Chiller",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791255",
                  name: "Hot Chocolate (S)",
                  price: 5100,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791261",
                  name: "Mocha (R)",
                  price: 14200,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791272",
                  name: "American Mud Pie",
                  price: 6300,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791260",
                  name: "Hot Chocolate (R)",
                  price: 8400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "93041905",
                  name: "Latte (R)",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
              ],
              maxAddons: 1,
              maxFreeAddons: -1,
            },
          ],
          itemAttribute: {
            vegClassifier: "NONVEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.3",
              ratingCount: "17 ratings",
              ratingCountV2: "17",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "115128848",
          name: "McSaver Veg Maharaja Mac Meal",
          category: "Gourmet Burger and Meals",
          description:
            "Enjoy a double decker Veg Maharaja Mac+ Fries (M) + Drink of your Choice . Order now to experience a customizable, delicious meal.",
          imageId: "2d1fb87e784f0645cc23087039366d3d",
          inStock: 1,
          isVeg: 1,
          price: 38477,
          variants: {},
          variantsV2: {},
          addons: [
            {
              groupId: "88794549",
              groupName: "Choose an option",
              choices: [
                {
                  id: "67791259",
                  name: "Cappuccino (R)",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791254",
                  name: "Sprite",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791265",
                  name: "McCafe-Chocolate Frappe",
                  price: 18400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791253",
                  name: "Fanta",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791264",
                  name: "Strawberry Chiller",
                  price: 8600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791263",
                  name: "McCafe-Mocha Frappe",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791274",
                  name: "Berry Lemonade Splash Regular",
                  price: 3800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791269",
                  name: "Lemon Chiller",
                  price: 4800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791257",
                  name: "Mocha (S)",
                  price: 11600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791268",
                  name: "McCafe-Ice Coffee",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791256",
                  name: "Latte (S)",
                  price: 3700,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791267",
                  name: "Green Apple Chiller",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791255",
                  name: "Hot Chocolate (S)",
                  price: 5100,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791261",
                  name: "Mocha (R)",
                  price: 14200,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791272",
                  name: "American Mud Pie",
                  price: 6300,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791260",
                  name: "Hot Chocolate (R)",
                  price: 8400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "93041905",
                  name: "Latte (R)",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
              ],
              maxAddons: 1,
              maxFreeAddons: -1,
            },
          ],
          itemAttribute: {
            vegClassifier: "VEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.2",
              ratingCount: "9 ratings",
              ratingCountV2: "9",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "58763395",
          name: "Big Spicy Paneer Wrap",
          category: "Burgers & Wraps",
          description:
            "Rich & filling cottage cheese patty coated in spicy crispy batter, topped with tom mayo sauce wrapped with lettuce, onions, tomatoes & cheese",
          imageId: "4938ed937ee5d59241ad94d772c7d7df",
          inStock: 1,
          isVeg: 1,
          price: 21000,
          variants: {},
          variantsV2: {},
          itemAttribute: {
            vegClassifier: "VEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.4",
              ratingCount: "43 ratings",
              ratingCountV2: "43",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "58763489",
          name: "McSpicy Chicken Burger",
          category: "Burgers & Wraps",
          description:
            "Tender and juicy chicken patty coated in spicy, crispy batter topped with a creamy sauce and crispy shredded lettuce will have you craving for more.",
          imageId: "61578655eb412c138b5c278bc271cd33",
          inStock: 1,
          price: 18476,
          variants: {},
          variantsV2: {},
          itemAttribute: {
            vegClassifier: "NONVEG",
          },
          ribbon: {
            text: "Bestseller",
            textColor: "#ffffff",
            topBackgroundColor: "#d53d4c",
            bottomBackgroundColor: "#b02331",
          },
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          isBestseller: true,
          ratings: {
            aggregatedRating: {
              rating: "4.2",
              ratingCount: "189 ratings",
              ratingCountV2: "189",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "58763498",
          name: "Big Spicy Chicken Wrap",
          category: "Burgers & Wraps",
          description:
            "Tender and juicy chicken patty coated in spicy, crispy batter, topped with a creamy sauce, wrapped with lettuce, onions, tomatoes & seasoning and cheese. A BIG indulgence.",
          imageId: "ec7f6a307d3680c0c330b20f9fedb646",
          inStock: 1,
          price: 22762,
          variants: {},
          variantsV2: {},
          itemAttribute: {
            vegClassifier: "NONVEG",
          },
          ribbon: {
            text: "Bestseller",
            textColor: "#ffffff",
            topBackgroundColor: "#d53d4c",
            bottomBackgroundColor: "#b02331",
          },
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          isBestseller: true,
          ratings: {
            aggregatedRating: {
              rating: "4.3",
              ratingCount: "91 ratings",
              ratingCountV2: "91",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "58763519",
          name: "McSpicy Paneer Burger",
          category: "Burgers & Wraps",
          description:
            "Rich and filling cottage cheese patty coated in spicy, crispy batter topped with a creamy sauce and crispy shredded lettuce will have you craving for more.",
          imageId: "aa4d7f79432310ac35bf6b7560196486",
          inStock: 1,
          isVeg: 1,
          price: 20000,
          variants: {},
          variantsV2: {},
          itemAttribute: {
            vegClassifier: "VEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.3",
              ratingCount: "50 ratings",
              ratingCountV2: "50",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "68263681",
          name: "Chicken Maharaja Mac",
          category: "Burgers & Wraps",
          description:
            "Enjoy the tallest burgers innovated by us. Created with chunky juicy grilled chicken patty paired along with fresh ingredients like jalape??o, onion, slice of cheese, tomatoes & crunchy lettuce dressed with the classical Habanero sauce.",
          imageId: "106e6e88e435a05c69e170534dc7f5e6",
          inStock: 1,
          price: 24667,
          variants: {},
          variantsV2: {},
          itemAttribute: {
            vegClassifier: "NONVEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.3",
              ratingCount: "59 ratings",
              ratingCountV2: "59",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "68263746",
          name: "Veg Maharaja Mac",
          category: "Burgers & Wraps",
          description:
            "Enjoy the tallest burgers innovated by us. Created with perfectly fried corn and cheese patty paired along with fresh ingredients like jalape??o, onion, slice of cheese & crunchy lettuce dressed with cocktail sauce.",
          imageId: "b85e6c16297b0c9127b8d08c93293cf7",
          inStock: 1,
          isVeg: 1,
          price: 22000,
          variants: {},
          variantsV2: {},
          itemAttribute: {
            vegClassifier: "VEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.4",
              ratingCount: "21 ratings",
              ratingCountV2: "21",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "58763576",
          name: "McSaver Chicken Maharaja Mac Meal",
          category: "EZ Delivery Meals",
          description:
            "Enjoy a double decker Chicken Maharaja Mac + Fries (M) + Drink of your Choice . Order now to experience a customizable, delicious meal.",
          imageId: "97932df813e65713ddd0808e77bb201e",
          inStock: 1,
          price: 38477,
          variants: {},
          variantsV2: {},
          addons: [
            {
              groupId: "88794434",
              groupName: "Choose an option",
              choices: [
                {
                  id: "67791259",
                  name: "Cappuccino (R)",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791254",
                  name: "Sprite",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791265",
                  name: "McCafe-Chocolate Frappe",
                  price: 18400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791253",
                  name: "Fanta",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791264",
                  name: "Strawberry Chiller",
                  price: 8600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791263",
                  name: "McCafe-Mocha Frappe",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791274",
                  name: "Berry Lemonade Splash Regular",
                  price: 3800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791269",
                  name: "Lemon Chiller",
                  price: 4800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791257",
                  name: "Mocha (S)",
                  price: 11600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791268",
                  name: "McCafe-Ice Coffee",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791256",
                  name: "Latte (S)",
                  price: 3700,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791267",
                  name: "Green Apple Chiller",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791255",
                  name: "Hot Chocolate (S)",
                  price: 5100,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791261",
                  name: "Mocha (R)",
                  price: 14200,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791272",
                  name: "American Mud Pie",
                  price: 6300,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791260",
                  name: "Hot Chocolate (R)",
                  price: 8400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "93041905",
                  name: "Latte (R)",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
              ],
              maxAddons: 1,
              maxFreeAddons: -1,
            },
          ],
          itemAttribute: {
            vegClassifier: "NONVEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.3",
              ratingCount: "17 ratings",
              ratingCountV2: "17",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "58763587",
          name: "McSaver McSpicy Chicken Meal",
          category: "EZ Delivery Meals",
          description:
            "Scrumptiously filling McSpicy Chicken Burger + Fries (M) + Drink of your choice.",
          imageId: "acbac72661f1c1c17ed7869fc05b8b5c",
          inStock: 1,
          price: 32858,
          variants: {},
          variantsV2: {},
          addons: [
            {
              groupId: "88794536",
              groupName: "Choose an option",
              choices: [
                {
                  id: "67791259",
                  name: "Cappuccino (R)",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791254",
                  name: "Sprite",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791265",
                  name: "McCafe-Chocolate Frappe",
                  price: 18400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791253",
                  name: "Fanta",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791264",
                  name: "Strawberry Chiller",
                  price: 8600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791263",
                  name: "McCafe-Mocha Frappe",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791274",
                  name: "Berry Lemonade Splash Regular",
                  price: 3800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791269",
                  name: "Lemon Chiller",
                  price: 4800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791257",
                  name: "Mocha (S)",
                  price: 11600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791268",
                  name: "McCafe-Ice Coffee",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791256",
                  name: "Latte (S)",
                  price: 3700,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791267",
                  name: "Green Apple Chiller",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791255",
                  name: "Hot Chocolate (S)",
                  price: 5100,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791261",
                  name: "Mocha (R)",
                  price: 14200,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791272",
                  name: "American Mud Pie",
                  price: 6300,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791260",
                  name: "Hot Chocolate (R)",
                  price: 8400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "93041905",
                  name: "Latte (R)",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
              ],
              maxAddons: 1,
              maxFreeAddons: -1,
            },
          ],
          itemAttribute: {
            vegClassifier: "NONVEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "3.8",
              ratingCount: "40 ratings",
              ratingCountV2: "40",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "58763590",
          name: "McSaver McSpicy Paneer Meal",
          category: "EZ Delivery Meals",
          description:
            "Enjoy a crispy McSpicy Paneer Burger + Fries (M) + Drink of your Choice . Order now to experience a customizable, delicious meal. Save Rs.50 on this Meal.",
          imageId: "8fe799db592880577db318963dd83720",
          inStock: 1,
          isVeg: 1,
          price: 31524,
          variants: {},
          variantsV2: {},
          addons: [
            {
              groupId: "88794539",
              groupName: "Choose an option",
              choices: [
                {
                  id: "67791259",
                  name: "Cappuccino (R)",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791254",
                  name: "Sprite",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791265",
                  name: "McCafe-Chocolate Frappe",
                  price: 18400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791253",
                  name: "Fanta",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791264",
                  name: "Strawberry Chiller",
                  price: 8600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791263",
                  name: "McCafe-Mocha Frappe",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791274",
                  name: "Berry Lemonade Splash Regular",
                  price: 3800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791269",
                  name: "Lemon Chiller",
                  price: 4800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791257",
                  name: "Mocha (S)",
                  price: 11600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791268",
                  name: "McCafe-Ice Coffee",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791256",
                  name: "Latte (S)",
                  price: 3700,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791267",
                  name: "Green Apple Chiller",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791255",
                  name: "Hot Chocolate (S)",
                  price: 5100,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791261",
                  name: "Mocha (R)",
                  price: 14200,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791272",
                  name: "American Mud Pie",
                  price: 6300,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791260",
                  name: "Hot Chocolate (R)",
                  price: 8400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "93041905",
                  name: "Latte (R)",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
              ],
              maxAddons: 1,
              maxFreeAddons: -1,
            },
          ],
          itemAttribute: {
            vegClassifier: "VEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "3.8",
              ratingCount: "10 ratings",
              ratingCountV2: "10",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "58763602",
          name: "McSaver McChicken Meal",
          category: "EZ Delivery Meals",
          description:
            "Your favorite McChicken Burger + Fries (M) + Drink of your choice.",
          imageId: "f8d6a90da313e5be870110ebdefb5bf6",
          inStock: 1,
          price: 30477,
          variants: {},
          variantsV2: {},
          addons: [
            {
              groupId: "88794535",
              groupName: "Choose an option",
              choices: [
                {
                  id: "67791259",
                  name: "Cappuccino (R)",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791254",
                  name: "Sprite",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791265",
                  name: "McCafe-Chocolate Frappe",
                  price: 18400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791253",
                  name: "Fanta",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791264",
                  name: "Strawberry Chiller",
                  price: 8600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791263",
                  name: "McCafe-Mocha Frappe",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791274",
                  name: "Berry Lemonade Splash Regular",
                  price: 3800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791269",
                  name: "Lemon Chiller",
                  price: 4800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791257",
                  name: "Mocha (S)",
                  price: 11600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791268",
                  name: "McCafe-Ice Coffee",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791256",
                  name: "Latte (S)",
                  price: 3700,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791267",
                  name: "Green Apple Chiller",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791255",
                  name: "Hot Chocolate (S)",
                  price: 5100,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791261",
                  name: "Mocha (R)",
                  price: 14200,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791272",
                  name: "American Mud Pie",
                  price: 6300,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791260",
                  name: "Hot Chocolate (R)",
                  price: 8400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "93041905",
                  name: "Latte (R)",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
              ],
              maxAddons: 1,
              maxFreeAddons: -1,
            },
          ],
          itemAttribute: {
            vegClassifier: "NONVEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.3",
              ratingCount: "18 ratings",
              ratingCountV2: "18",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "58763617",
          name: "McSaver Big Spicy Chicken Wrap Meal",
          category: "EZ Delivery Meals",
          description:
            "Treat yourself with a Big Spicy Chicken Wrap + Fries (M) + Drink of your choice.",
          imageId: "c92aad0176202cf0a53a2b3c38cb5468",
          inStock: 1,
          price: 40191,
          variants: {},
          variantsV2: {},
          addons: [
            {
              groupId: "88794418",
              groupName: "Choose an option",
              choices: [
                {
                  id: "67791259",
                  name: "Cappuccino (R)",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791254",
                  name: "Sprite",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791265",
                  name: "McCafe-Chocolate Frappe",
                  price: 18400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791253",
                  name: "Fanta",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791264",
                  name: "Strawberry Chiller",
                  price: 8600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791263",
                  name: "McCafe-Mocha Frappe",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791274",
                  name: "Berry Lemonade Splash Regular",
                  price: 3800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791269",
                  name: "Lemon Chiller",
                  price: 4800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791257",
                  name: "Mocha (S)",
                  price: 11600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791268",
                  name: "McCafe-Ice Coffee",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791256",
                  name: "Latte (S)",
                  price: 3700,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791267",
                  name: "Green Apple Chiller",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791255",
                  name: "Hot Chocolate (S)",
                  price: 5100,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791261",
                  name: "Mocha (R)",
                  price: 14200,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791272",
                  name: "American Mud Pie",
                  price: 6300,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791260",
                  name: "Hot Chocolate (R)",
                  price: 8400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "93041905",
                  name: "Latte (R)",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
              ],
              maxAddons: 1,
              maxFreeAddons: -1,
            },
          ],
          itemAttribute: {
            vegClassifier: "NONVEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.7",
              ratingCount: "3 ratings",
              ratingCountV2: "3",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "58763621",
          name: "McSaver Veg Maharaja Mac Meal",
          category: "EZ Delivery Meals",
          description:
            "Enjoy a double decker Veg Maharaja Mac+ Fries (M) + Drink of your Choice . Order now to experience a customizable, delicious meal.",
          imageId: "2d1fb87e784f0645cc23087039366d3d",
          inStock: 1,
          isVeg: 1,
          price: 38477,
          variants: {},
          variantsV2: {},
          addons: [
            {
              groupId: "88794546",
              groupName: "Choose an option",
              choices: [
                {
                  id: "67791259",
                  name: "Cappuccino (R)",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791254",
                  name: "Sprite",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791265",
                  name: "McCafe-Chocolate Frappe",
                  price: 18400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791253",
                  name: "Fanta",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791264",
                  name: "Strawberry Chiller",
                  price: 8600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791263",
                  name: "McCafe-Mocha Frappe",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791274",
                  name: "Berry Lemonade Splash Regular",
                  price: 3800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791269",
                  name: "Lemon Chiller",
                  price: 4800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791257",
                  name: "Mocha (S)",
                  price: 11600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791268",
                  name: "McCafe-Ice Coffee",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791256",
                  name: "Latte (S)",
                  price: 3700,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791267",
                  name: "Green Apple Chiller",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791255",
                  name: "Hot Chocolate (S)",
                  price: 5100,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791261",
                  name: "Mocha (R)",
                  price: 14200,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791272",
                  name: "American Mud Pie",
                  price: 6300,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791260",
                  name: "Hot Chocolate (R)",
                  price: 8400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "93041905",
                  name: "Latte (R)",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
              ],
              maxAddons: 1,
              maxFreeAddons: -1,
            },
          ],
          itemAttribute: {
            vegClassifier: "VEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.2",
              ratingCount: "9 ratings",
              ratingCountV2: "9",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "58763623",
          name: "McSaver McVeggie Meal",
          category: "EZ Delivery Meals",
          description:
            "Enjoy a combo of McVeggie + Fries (M) + Drink of your Choice . Order now to experience a customizable, delicious meal. Save Rs.50 on this Meal.",
          imageId: "8dde65bd07bc06dd061b3bce0c52669f",
          inStock: 1,
          isVeg: 1,
          price: 27905,
          variants: {},
          variantsV2: {},
          addons: [
            {
              groupId: "88794542",
              groupName: "Choose an option",
              choices: [
                {
                  id: "67791259",
                  name: "Cappuccino (R)",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791254",
                  name: "Sprite",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791265",
                  name: "McCafe-Chocolate Frappe",
                  price: 18400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791253",
                  name: "Fanta",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791264",
                  name: "Strawberry Chiller",
                  price: 8600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791263",
                  name: "McCafe-Mocha Frappe",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791274",
                  name: "Berry Lemonade Splash Regular",
                  price: 3800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791269",
                  name: "Lemon Chiller",
                  price: 4800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791257",
                  name: "Mocha (S)",
                  price: 11600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791268",
                  name: "McCafe-Ice Coffee",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791256",
                  name: "Latte (S)",
                  price: 3700,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791267",
                  name: "Green Apple Chiller",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791255",
                  name: "Hot Chocolate (S)",
                  price: 5100,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791261",
                  name: "Mocha (R)",
                  price: 14200,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791272",
                  name: "American Mud Pie",
                  price: 6300,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791260",
                  name: "Hot Chocolate (R)",
                  price: 8400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "93041905",
                  name: "Latte (R)",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
              ],
              maxAddons: 1,
              maxFreeAddons: -1,
            },
          ],
          itemAttribute: {
            vegClassifier: "VEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.4",
              ratingCount: "11 ratings",
              ratingCountV2: "11",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "60741671",
          name: "McSaver Mexican McAloo Tikki Meal",
          category: "EZ Delivery Meals",
          description:
            "Enjoy a combo of Mexican McAloo Tikki + Fries (M) + Drink of your Choice . Order now to experience a customizable, delicious meal.",
          imageId: "60af83b4babdb6e4ad77d3498f32841c",
          inStock: 1,
          isVeg: 1,
          price: 21524,
          variants: {},
          variantsV2: {},
          addons: [
            {
              groupId: "82870020",
              groupName: "Choose an option",
              choices: [
                {
                  id: "67791259",
                  name: "Cappuccino (R)",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791254",
                  name: "Sprite",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791265",
                  name: "McCafe-Chocolate Frappe",
                  price: 18400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791253",
                  name: "Fanta",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791264",
                  name: "Strawberry Chiller",
                  price: 8600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791263",
                  name: "McCafe-Mocha Frappe",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791274",
                  name: "Berry Lemonade Splash Regular",
                  price: 3800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791269",
                  name: "Lemon Chiller",
                  price: 4800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791257",
                  name: "Mocha (S)",
                  price: 11600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791268",
                  name: "McCafe-Ice Coffee",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791256",
                  name: "Latte (S)",
                  price: 3700,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791267",
                  name: "Green Apple Chiller",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791255",
                  name: "Hot Chocolate (S)",
                  price: 5100,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791261",
                  name: "Mocha (R)",
                  price: 14200,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791272",
                  name: "American Mud Pie",
                  price: 6300,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791260",
                  name: "Hot Chocolate (R)",
                  price: 8400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "93041905",
                  name: "Latte (R)",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
              ],
              maxAddons: 1,
              maxFreeAddons: -1,
            },
          ],
          itemAttribute: {
            vegClassifier: "VEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.4",
              ratingCount: "17 ratings",
              ratingCountV2: "17",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "80627217",
          name: "McSaver McSpicy Premium Chicken Meal",
          category: "EZ Delivery Meals",
          description:
            "A deliciously filling meal of McSpicy Premium Chicken Burger + Fries (M) + Drink of your choice",
          imageId: "d437eb722f457c66f26a087b789c056f",
          inStock: 1,
          price: 38477,
          variants: {},
          variantsV2: {},
          addons: [
            {
              groupId: "82870014",
              groupName: "Choose an option",
              choices: [
                {
                  id: "67791259",
                  name: "Cappuccino (R)",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791254",
                  name: "Sprite",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791265",
                  name: "McCafe-Chocolate Frappe",
                  price: 18400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791253",
                  name: "Fanta",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791264",
                  name: "Strawberry Chiller",
                  price: 8600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791263",
                  name: "McCafe-Mocha Frappe",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791274",
                  name: "Berry Lemonade Splash Regular",
                  price: 3800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791269",
                  name: "Lemon Chiller",
                  price: 4800,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791257",
                  name: "Mocha (S)",
                  price: 11600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791268",
                  name: "McCafe-Ice Coffee",
                  price: 10600,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791256",
                  name: "Latte (S)",
                  price: 3700,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791267",
                  name: "Green Apple Chiller",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791255",
                  name: "Hot Chocolate (S)",
                  price: 5100,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791261",
                  name: "Mocha (R)",
                  price: 14200,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791272",
                  name: "American Mud Pie",
                  price: 6300,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "67791260",
                  name: "Hot Chocolate (R)",
                  price: 8400,
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  id: "93041905",
                  name: "Latte (R)",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
              ],
              maxAddons: 1,
              maxFreeAddons: -1,
            },
          ],
          itemAttribute: {
            vegClassifier: "NONVEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.1",
              ratingCount: "15 ratings",
              ratingCountV2: "15",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "63149616",
          name: "McChicken + Fries (M)",
          category: "Sharing Meals",
          description: "McChicken + Fries (M)",
          imageId: "5c4ddd549b9709a00abc94412eec940c",
          inStock: 1,
          price: 18000,
          variants: {},
          variantsV2: {},
          itemAttribute: {
            vegClassifier: "NONVEG",
          },
          ribbon: {
            text: "Bestseller",
            textColor: "#ffffff",
            topBackgroundColor: "#d53d4c",
            bottomBackgroundColor: "#b02331",
          },
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          isBestseller: true,
          ratings: {
            aggregatedRating: {
              rating: "4.3",
              ratingCount: "122 ratings",
              ratingCountV2: "122",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "63149617",
          name: "McVeggie + Fries (M)",
          category: "Sharing Meals",
          description: "McVeggie + Fries (M)",
          imageId: "1e5b0dcafb10c371d916c0dabf1b2c72",
          inStock: 1,
          isVeg: 1,
          price: 18952,
          variants: {},
          variantsV2: {},
          itemAttribute: {
            vegClassifier: "VEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.2",
              ratingCount: "24 ratings",
              ratingCountV2: "24",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "87285298",
          name: "2 McVeggie Burger",
          category: "Sharing Meals",
          description: "2 McVeggie Burger",
          imageId: "c2a0690ec46c882f768a841a4b7255f8",
          inStock: 1,
          isVeg: 1,
          price: 19619,
          variants: {},
          variantsV2: {},
          itemAttribute: {
            vegClassifier: "VEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.7",
              ratingCount: "35 ratings",
              ratingCountV2: "35",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "102107632",
          name: "McVeggie Burger + Veg Pizza McPuff + Fries (L)",
          category: "Sharing Meals",
          description:
            "Flat 15% Off on McVeggie Burger + Veg Pizza McPuff + Fries (L)",
          imageId: "fa264b9e34561160f447c2f5f3f71713",
          inStock: 1,
          isVeg: 1,
          price: 25810,
          variants: {},
          variantsV2: {},
          itemAttribute: {
            vegClassifier: "VEG",
          },
          ribbon: {},
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          ratings: {
            aggregatedRating: {
              rating: "4.5",
              ratingCount: "8 ratings",
              ratingCountV2: "8",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
    {
      card: {
        "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
        info: {
          id: "65331755",
          name: "Fries (L)",
          category: "Sides & Dips",
          description:
            "World Famous Fries, crispy golden, fried to perfection and lightly salted. Also known as happiness.",
          imageId: "a7c5c444faf5f8e9fbd5d0be085826dc",
          inStock: 1,
          isVeg: 1,
          price: 13048,
          variants: {},
          variantsV2: {},
          itemAttribute: {
            vegClassifier: "VEG",
          },
          ribbon: {
            text: "Bestseller",
            textColor: "#ffffff",
            topBackgroundColor: "#d53d4c",
            bottomBackgroundColor: "#b02331",
          },
          showImage: true,
          itemBadge: {},
          badgesV2: {},
          isBestseller: true,
          ratings: {
            aggregatedRating: {
              rating: "4.3",
              ratingCount: "148 ratings",
              ratingCountV2: "148",
            },
          },
        },
        analytics: {},
        hideRestaurantDetails: true,
      },
    },
  ],
  type: "CATEGORY_TYPE_RECOMMENDED",
};

export default resMenu;
